# Generated by Django 4.2.18 on 2025-02-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='attributimages/'),
        ),
        migrations.AddField(
            model_name='option',
            name='is_a_variable_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('grey', 'Grey'), ('blue', 'Blue'), ('black', 'Black'), ('yellow', 'Yellow'), ('red', 'Red'), ('white', 'White')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_class_option_names',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='variants',
            field=models.CharField(choices=[('-----', '------'), ('colors', 'Colors'), ('materials', 'Materials')], default='-----', max_length=20, verbose_name='variants'),
        ),
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('date', 'Date'), ('select', 'Select'), ('radio', 'Radio'), ('multi_select', 'Multi select'), ('checkbox', 'Checkbox'), ('image', 'Image')], default='text', max_length=255, verbose_name='Type'),
        ),
    ]
